when:
  - event: push
    branch: master

steps:
  - name: release
    image: node:22-alpine
    environment:
      NPM_TOKEN:
        from_secret: NPM_TOKEN
      GH_TOKEN:
        from_secret: GH_TOKEN
    commands:
      - apk add --no-cache git
      - yarn install --frozen-lockfile
      - git config user.name "release-bot"
      - git config user.email "ci@awtomated.com"
      - yarn release
